language: python
python:
    - "3.7"

services:
    - docker

before_script:
    - echo "DB_PASS=$DB_PASS" > .env
    - echo "SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN" >> .env
    - echo "SLACK_USER_TOKEN=$SLACK_USER_TOKEN" >> .env

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda env create -f environment.yml -n digest
    - source activate digest

# start containers -> sleep 10 secs -> get restart count of running containers -> sum restart count and check == 0
script:
    - docker-compose up -d
    - sleep 10
    - docker inspect --format "{{.RestartCount}}" $(docker ps -aq) | paste -sd+ | bc | xargs test 0 -eq && echo "No restarts happened" && docker container ls && exit 0 || echo "restarts happened" && docker-compose logs && travis_terminate 1
    - python -m unittest discover -s tests
