version: '3'
services:
  uiservice:
    build:
      context: .
      dockerfile: uiservice/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:80"
    depends_on:
      - dbservice
    env_file:
      - .env

  crawler:
    build:
      context: .
      dockerfile: crawler/Dockerfile
    restart: always
    depends_on:
      - dbservice
    env_file:
      - .env

  timers:
    build:
      context: .
      dockerfile: timers/Dockerfile
    restart: always
    depends_on:
      - dbservice
      - uiservice
    env_file:
      - .env

  dbservice:
    build:
      context: .
      dockerfile: dbservice/Dockerfile
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
