version: '3'
services:
  bot:
    build: .
    restart: always
    depends_on:
      - postgres
      - crawler # TODO: remove, now just to avoid double tables creation
    env_file:
      - .env

  crawler:
    build:
      context: .
      dockerfile: crawler/Dockerfile
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
