name: digest
channels:
  - defaults
  - conda-forge
dependencies:
  - aiohttp==3.6.1
  - psycopg2=2.8.3
  - python=3.7.4
  - asyncpg=0.18.3
  - async-timeout==3.0.1
  - attrs==19.2.0
  - chardet==3.0.4
  - idna==2.8
  - yarl==1.3.0
  - multidict==4.5.2
  - nest-asyncio==1.2.0
  - typing-extensions==3.7.4
  - urllib3==1.25.6
  - websocket-client==0.54.0
  - pip=19.2.3
  - pip:
    - idna-ssl==1.1.0
    - slackclient==2.2.1